cd "%~dp0"

REM ren assets\data.win game.droid

aapt add -f -v AM2RWrapper.apk^
 assets/AM2R.ini^
 assets/game.droid^
 assets/lang/english.ini^
 assets/lang/french.ini^
 assets/lang/czech.ini^
 assets/lang/german.ini^
 assets/lang/spanish.ini^
 assets/lang/russian.ini^
 assets/lang/japanese.ini^
 assets/lang/italian.ini^
 assets/lang/languages.txt^
 assets/lang/fonts/04b09.ttf^
 assets/lang/fonts/04b24.ttf^
 assets/lang/fonts/Acknowledge_TT_BRK.ttf^
 assets/lang/fonts/Glasstown_NBP.ttf^
 assets/lang/fonts/uni_05_53.ttf^
 assets/lang/headers/castellano_a1_f24_b0_c3_d19_e21.png^
 assets/lang/headers/castellano_a2_f31_b0_c3_d26_e28.png^
 assets/lang/headers/castellano_a3_f30_b0_c3_d25_e27.png^
 assets/lang/headers/castellano_a4_f19_b0_c3_d14_e16.png^
 assets/lang/headers/castellano_a5_f32_b0_c3_d27_e29.png^
 assets/lang/headers/castellano_a7_f19_b0_c7_d9_e17.png^
 assets/lang/headers/castellano_a8_f20_b0_c7_d15_e17.png^
 assets/lang/headers/deutsch_a1_f26_b0_c3_d21_e23.png^
 assets/lang/headers/deutsch_a2_f22_b0_c3_d17_e19.png^
 assets/lang/headers/deutsch_a3_f28_b0_c3_d23_e25.png^
 assets/lang/headers/deutsch_a4_f19_b0_c3_d14_e16.png^
 assets/lang/headers/deutsch_a5_f28_b0_c3_d23_e25.png^
 assets/lang/headers/deutsch_a7_f19_b0_c7_d9_e17.png^
 assets/lang/headers/francais_a1_f22_b0_c3_d17_e19.png^
 assets/lang/headers/francais_a2_f25_b0_c3_d20_e22.png^
 assets/lang/headers/francais_a3_f30_b0_c3_d25_e27.png^
 assets/lang/headers/francais_a4_f18_b0_c3_d13_e15.png^
 assets/lang/headers/francais_a5_f32_b0_c3_d27_e29.png^
 assets/lang/headers/francais_a7_f19_b0_c7_d9_e17.png^
 assets/lang/headers/francais_a8_f20_b0_c7_d15_e17.png^
 assets/lang/headers/italiano_a1_f26_b0_c3_d21_e23.png^
 assets/lang/headers/italiano_a2_f26_b0_c3_d21_e23.png^
 assets/lang/headers/italiano_a3_f32_b0_c3_d27_e29.png^
 assets/lang/headers/italiano_a4_f19_b0_c3_d14_e16.png^
 assets/lang/headers/italiano_a5_f33_b0_c3_d28_e30.png^
 assets/lang/headers/italiano_a7_f19_b0_c7_d9_e17.png^
 assets/lang/headers/italiano_a8_f20_b0_c7_d15_e17.png^
 assets/lang/headers/japanese_a1_f16_b0_c3_d11_e13.png^
 assets/lang/headers/japanese_a2_f16_b0_c3_d11_e13.png^
 assets/lang/headers/japanese_a3_f16_b0_c3_d11_e13.png^
 assets/lang/headers/japanese_a4_f15_b0_c3_d10_e12.png^
 assets/lang/headers/japanese_a5_f18_b0_c3_d13_e15.png^
 assets/lang/headers/japanese_a7_f19_b0_c7_d9_e17.png^
 assets/lang/headers/japanese_a8_f20_b0_c3_d15_e17.png^
 assets/lang/headers/russian_a1_f23_b0_c3_d18_e20.png^
 assets/lang/headers/russian_a2_f24_b0_c3_d19_e21.png^
 assets/lang/headers/russian_a3_f22_b0_c3_d17_e19.png^
 assets/lang/headers/russian_a4_f17_b0_c3_d12_e14.png^
 assets/lang/headers/russian_a5_f30_b0_c3_d25_e27.png^
 assets/lang/headers/russian_a7_f19_b0_c7_d9_e17.png^
 assets/lang/headers/russian_a8_f19_b0_c3_d14_e16.png^
 assets/musalphafight.ogg^
 assets/musancientguardian.ogg^
 assets/musarachnus.ogg^
 assets/musarea1a.ogg^
 assets/musarea1b.ogg^
 assets/musarea2a.ogg^
 assets/musarea2b.ogg^
 assets/musarea3a.ogg^
 assets/musarea3b.ogg^
 assets/musarea4a.ogg^
 assets/musarea4b.ogg^
 assets/musarea5a.ogg^
 assets/musarea5b.ogg^
 assets/musarea6a.ogg^
 assets/musarea7a.ogg^
 assets/musarea7b.ogg^
 assets/musarea7c.ogg^
 assets/musarea7d.ogg^
 assets/musarea8.ogg^
 assets/muscaveambience.ogg^
 assets/muscaveambiencea4.ogg^
 assets/muscredits.ogg^
 assets/musending.ogg^
 assets/museris.ogg^
 assets/musfanfare.ogg^
 assets/musgammafight.ogg^
 assets/musgenesis.ogg^
 assets/mushatchling.ogg^
 assets/musintroseq.ogg^
 assets/musitemamb.ogg^
 assets/musitemget.ogg^
 assets/muslabambience.ogg^
 assets/musmaincave.ogg^
 assets/musmaincave2.ogg^
 assets/musmetroidappear.ogg^
 assets/musomegafight.ogg^
 assets/musqueen.ogg^
 assets/musqueen2.ogg^
 assets/musqueen3.ogg^
 assets/musqueenbreak.ogg^
 assets/musqueenintro.ogg^
 assets/musreactor.ogg^
 assets/mustitle.ogg^
 assets/mustorizoa.ogg^
 assets/mustorizob.ogg^
 assets/muszetafight.ogg

ECHO.
ECHO Signing Android APK...
java -jar uber-apk-signer.jar -a AM2RWrapper.apk

del AM2RWrapper.apk
